package com.concentration.entity;

import java.util.Date;

public class Logs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.deleted
     *
     * @mbggenerated
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_key
     *
     * @mbggenerated
     */
    private String logKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    public Logs(Long id, Date createTime, Byte deleted, Date updateTime, String content, String ipAddress, String logKey, Integer type) {
        this.id = id;
        this.createTime = createTime;
        this.deleted = deleted;
        this.updateTime = updateTime;
        this.content = content;
        this.ipAddress = ipAddress;
        this.logKey = logKey;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    public Logs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.id
     *
     * @return the value of logs.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.id
     *
     * @param id the value for logs.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.create_time
     *
     * @return the value of logs.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.create_time
     *
     * @param createTime the value for logs.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.deleted
     *
     * @return the value of logs.deleted
     *
     * @mbggenerated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.deleted
     *
     * @param deleted the value for logs.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.update_time
     *
     * @return the value of logs.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.update_time
     *
     * @param updateTime the value for logs.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.content
     *
     * @return the value of logs.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.content
     *
     * @param content the value for logs.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.ip_address
     *
     * @return the value of logs.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.ip_address
     *
     * @param ipAddress the value for logs.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_key
     *
     * @return the value of logs.log_key
     *
     * @mbggenerated
     */
    public String getLogKey() {
        return logKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_key
     *
     * @param logKey the value for logs.log_key
     *
     * @mbggenerated
     */
    public void setLogKey(String logKey) {
        this.logKey = logKey == null ? null : logKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.type
     *
     * @return the value of logs.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.type
     *
     * @param type the value for logs.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}